export enum UserRole {
  ADMIN = 'ADMIN',
  PROPRIETARIO = 'PROPRIETARIO',
  GERENTE = 'GERENTE',
  CAIXA = 'CAIXA',
  GARCOM = 'GARCOM',
  COZINHA = 'COZINHA',
  EXPEDICAO = 'EXPEDICAO',
  ENTREGADOR = 'ENTREGADOR',
  ESTOQUISTA = 'ESTOQUISTA',
  ATENDENTE = 'ATENDENTE',
  CLIENTE = 'CLIENTE'
}

export enum OrderType {
  DINE_IN = 'DINE_IN',
  TAKEAWAY = 'TAKEAWAY',
  COUNTER = 'COUNTER',
  DELIVERY = 'DELIVERY'
}

export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  IN_DISPATCH = 'IN_DISPATCH',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}
